### PR TITLE
Adding a frame by frame option on the player

### PR DESCRIPTION
**Pull request by thibserot**
#### What kind of change does this PR introduce? (check one with "x")
- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

#### What is the current behavior? (You can also link to an open issue here)
Only Play/Pause button available

#### What is the new behavior?
You can now enable via showFrameByFrame additional controls that will allow you to do a frame-by-frame play (+1,+5, -1, -5)

#### Does this PR introduce a breaking change? (check one with "x")
- [ ] Yes
- [x] No

Default values have been chosen so that it doesn't change current behavior

_If this PR contains a breaking change, please describe the impact and migration path for existing applications:_

N/A

### CODE REVIEW

**Comment by nkoehler** [comment]
I have removed the tooltips for consistency with the rest of the controls, and tslinted the code.

I was unsure about the new fps variable, because not many people will know the exact fps of their video.  But even if it is skipping 6/7/10 frames, it's not really a big issue.

Other than that the changes look fine.  Should be available in the next release.  Thank you for the contribution.

**Comment by thibserot** [comment]
I was hesitating with adding the tooltip for all control...The extra cost of importing this module is very low since you are already relying on material and it helps with readability. but if you prefer a tooltip free module I don't mind. And if you wish me to add an extra contribution to add tooltip on all control I'll do it with pleasure!

Thanks for merging so fast the PR :)

When do you think you'll be performing a release?

**Comment by nkoehler** [comment]
I'm going to leave tooltips out for now, as on other projects I've noticed that with 10+ tooltips there is a performance hit with all the event listeners that get registered.

Not a problem, I was working on the project today anyways.  I am hoping to cut a new release (with Angular 8 support as well) later today if all goes well.

**Comment by thibserot** [comment]
I just tried to integrate the new mat-video release 2.7.0 (I was using 2.6.0 before) and ng serve fails with :
ERROR in No NgModule metadata found for 'AppModule'.

I'm using Angular 7.x ....Have you tried it?
Could it be something that you did to enable Angular8 support?

**Pull request merged**
